spring:
  application.name: pretty-like-backend
  mvc:
    servlet:
      path: /api
  profiles:
    active: local
    # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxx
    username: xxx
    password: xxx
  pulsar:
    client:
      service-url: xxx

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.75, 0.9, 0.95, 0.99
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

# knife4j 的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn