spring:
  application.name: pretty-like-backend
  mvc:
    servlet:
      path: /api
  profiles:
    active: local
    # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxx
    username: xxx
    password: xxx
  data:
    redis:
      host: 47.109.99.11
      port: 6379
      password: YOLO123456abcde!!!
      database: 0
      timeout: 5000

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

# knife4j 的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn